# To install PyTorch CUDA:
# uv venv (only needed if the env hasn't been created yet)
# uv pip sync pyproject.toml
[project]
name = "node-editor-rf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-fasthtml", 
    "openai", 
    "pillow", 
    "python-dotenv", 
    "requests",
    "torch",
    "diffusers",
    "transformers",
    "accelerate",
	"xformers"
]

# Check the PyTorch index to find CUDA-enabled packages.
# This is required for GPU support.
[tool.uv.pip]
extra-index-url = ["https://download.pytorch.org/whl/cu121"]